import type { Restaurant } from './types';

/** design/0002 §7 的 12 类中间层；类别层是唯一真正在学习的层（ADR-0005） */
export const CATEGORY_OF: Record<string, string> = {
  CN_SICHUAN: 'CN_SPICY', CN_HOTPOT: 'CN_SPICY', CN_SKEWER: 'CN_SPICY', CN_HUNAN: 'CN_SPICY',
  CN_DIMSUM: 'CN_CANTONESE', CN_BBQ_MEAT: 'CN_CANTONESE', CN_HK_CAFE: 'CN_CANTONESE',
  CN_CANTON: 'CN_CANTONESE', CN_CONGEE: 'CN_CANTONESE',
  CN_NORTHEAST: 'CN_NORTHERN', CN_NOODLE: 'CN_NORTHERN', CN_DUMPLING: 'CN_NORTHERN', CN_XIBEI: 'CN_NORTHERN',
  CN_JIANGZHE: 'CN_SOUTHERN', CN_YUNNAN: 'CN_SOUTHERN', CN_TAIWAN: 'CN_SOUTHERN',
  CN_FAST: 'CN_CASUAL', CN_BREAKFAST: 'CN_CASUAL', CN_VEG: 'CN_CASUAL', CN_AMERICANIZED: 'CN_CASUAL',
  CN_DESSERT: 'CN_SWEET', CN_BUBBLETEA: 'CN_SWEET',
  AS_SUSHI: 'AS_JAPANESE', AS_IZAKAYA: 'AS_JAPANESE', AS_RAMEN: 'AS_JAPANESE', AS_DONBURI: 'AS_JAPANESE',
  AS_KOREAN: 'AS_KOREAN', AS_KBBQ: 'AS_KOREAN', AS_KFC_KOREAN: 'AS_KOREAN',
  AS_VIETNAM: 'AS_SEA', AS_THAI: 'AS_SEA', AS_MALAY: 'AS_SEA', AS_INDIAN: 'AS_SEA', AS_FILIPINO: 'AS_SEA',
  WS_BRUNCH: 'WS_WESTERN', WS_ITALIAN: 'WS_WESTERN', WS_STEAK: 'WS_WESTERN',
  WS_PIZZA: 'WS_CASUAL', WS_BURGER: 'WS_CASUAL', WS_DELI: 'WS_CASUAL', WS_MEXICAN: 'WS_CASUAL',
  WS_MIDEAST: 'WS_CASUAL', WS_GREEK: 'WS_CASUAL', WS_CARIBBEAN: 'WS_CASUAL',
  WS_BUFFET: 'WS_CASUAL', WS_CANADIAN: 'WS_CASUAL',
  WS_CAFE: 'WS_CAFE',
};

export function categoryOf(r: Restaurant): string {
  return CATEGORY_OF[r.primary] ?? r.primary.split('_')[0];
}

export const CATEGORY_LABELS: Record<string, string> = {
  CN_SPICY: '川湘火锅', CN_CANTONESE: '粤港', CN_NORTHERN: '北方面点',
  CN_SOUTHERN: '江浙云台', CN_CASUAL: '中式快餐', CN_SWEET: '甜品奶茶',
  AS_JAPANESE: '日料', AS_KOREAN: '韩餐', AS_SEA: '东南亚',
  WS_WESTERN: '西餐', WS_CASUAL: '西式简餐', WS_CAFE: '咖啡烘焙',
};
